### ISSUE TITLE
Get mypy working correctly in pre-commit with pydantic and sqlalchemy and correct settings

### ISSUE THREAD

**Issue by vladutmd** [CNLearn/backend#15]
If adding mypy to the pre-commit, it needs additional settings such as:

```
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.1.1"
    hooks:
      - id: mypy
        additional_dependencies:
          - "pydantic>=1.10.7"
          - "sqlalchemy>=2.0.8"
```

in order to work with the two plugins (from pydantic and sqlalchemy correctly). When doing that, it raises certain errors that running mypy directly doesn't. Need to figure out what's happening.
